# Generated by Django 4.1.7 on 2023-12-15 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255)),
                ('code', models.CharField(default='AD01', max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id_ass', models.AutoField(primary_key=True, serialize=False)),
                ('prix_par_jour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('matricule', models.CharField(max_length=50)),
                ('passenger_number', models.IntegerField()),
                ('air_conditioning', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('fuel', models.TextField(choices=[('ESSENCE', 'ESSENCE'), ('DIESEL', 'DIESEL')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChildChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('prix_jrs', models.IntegerField()),
                ('diponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id_pickup', models.AutoField(primary_key=True, serialize=False)),
                ('lieu', models.CharField(max_length=100)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_review', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'SUPERADMIN'), ('ADMIN', 'ADMIN')], default='ADMIN', max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('location_api.user',),
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id_tarif', models.AutoField(primary_key=True, serialize=False)),
                ('max_duration', models.IntegerField()),
                ('min_duration', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_api.car')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_booking', models.CharField(default='BK01', max_length=7, unique=True)),
                ('date_book', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('nbr_jrs', models.IntegerField()),
                ('etat', models.BooleanField(default=False)),
                ('payement', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tel', models.CharField(blank=True, max_length=25)),
                ('pays', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField()),
                ('cin_passport', models.CharField(blank=True, max_length=50)),
                ('assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_api.assurance')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_api.car')),
                ('childchair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_api.childchair')),
                ('pickup_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_pickup_end', to='location_api.pickuppoint')),
                ('pickup_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_pickup_start', to='location_api.pickuppoint')),
            ],
        ),
    ]
