# Generated by Django 4.1.7 on 2023-11-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('tel', models.CharField(blank=True, max_length=25)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_booking', models.CharField(default='BK01', max_length=7, unique=True)),
                ('date_book', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('payement', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50)),
                ('passenger_number', models.IntegerField()),
                ('air_conditioning', models.BooleanField(default=False)),
                ('disponibilte', models.BooleanField(default=True)),
                ('fuel', models.TextField(choices=[('ESSENCE', 'ESSENCE'), ('DIESEL', 'DIESEL')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('numCard', models.CharField(blank=True, max_length=20)),
                ('expDate', models.CharField(blank=True, max_length=7)),
                ('securityCode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id_pickup', models.AutoField(primary_key=True, serialize=False)),
                ('lieu', models.CharField(max_length=100)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10)),
                ('birthday', models.DateField()),
                ('tel', models.CharField(blank=True, max_length=25)),
                ('pays', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('license_number', models.CharField(max_length=50)),
                ('cin_passport', models.CharField(blank=True, max_length=50)),
                ('paiement', models.ManyToManyField(blank=True, related_name='users', to='location_api.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id_tarif', models.AutoField(primary_key=True, serialize=False)),
                ('max_duration', models.IntegerField()),
                ('min_duration', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_api.car')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='location_api.booking')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='location_api.user'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='location_api.car')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_api.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_pickup_end', to='location_api.pickuppoint'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_pickup_start', to='location_api.pickuppoint'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_api.user'),
        ),
    ]
