# Generated by Django 4.1.7 on 2023-12-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gearBox',
            field=models.TextField(choices=[('MANUELLE', 'MANUELLE'), ('AUTOMATIQUE', 'AUTOMATIQUE')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
