# Generated by Django 4.1.7 on 2023-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_api', '0003_alter_tarifs_min_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifs',
            old_name='max_duration',
            new_name='price_more_week',
        ),
        migrations.RenameField(
            model_name='tarifs',
            old_name='price_per_day',
            new_name='price_tree_days',
        ),
        migrations.RemoveField(
            model_name='tarifs',
            name='min_duration',
        ),
        migrations.AddField(
            model_name='tarifs',
            name='price_week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
