# Generated by Django 4.1.7 on 2023-12-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_api', '0004_rename_max_duration_tarifs_price_more_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifs',
            old_name='price_more_week',
            new_name='price_more_month',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='tarifs',
            name='price_more_two_week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifs',
            name='price_two_week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
