# Generated by Django 4.1.7 on 2023-12-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_api', '0005_rename_price_more_week_tarifs_price_more_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='code_booking',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='etat',
        ),
    ]
