# Generated by Django 4.1.7 on 2023-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_api', '0006_rename_code_booking_booking_code_remove_booking_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='conducteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='rehausseur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='assurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='childchair',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Assurance',
        ),
        migrations.DeleteModel(
            name='ChildChair',
        ),
    ]
