# Generated by Django 4.1.7 on 2023-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_api', '0007_booking_conducteur_booking_rehausseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price_HT',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
