# Generated by Django 4.1.7 on 2023-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_api', '0008_booking_total_price_ht'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='repayment',
            field=models.BooleanField(default=False),
        ),
    ]
